### PR TITLE
Update install.pp

### PR DESCRIPTION
**Pull request by mnothic**
add support to none default mnesia base

### CODE REVIEW

**Comment by nibalizer** [comment]
@mnothic can you squash these commits into one? Can you at the same time write a more complete commit message explaining what the change is and why you are doing it?

As for test failures, this is a simple linting problem. Double vs single quotes, should be easy to fix.

Thanks

**Comment by mnothic** [comment]
the module support mnesia environment variable set but when you setup it with another path which isn't the default the other task can't find the new directory and every else fails ok so the fix is for ensure the directory mnesia if is passed in the environment_variables hash

**Comment by bmjen** [comment]
Tests failing linting.

~~~
Skipping metadata validation; the metadata-json-lint gem was not found
manifests/install.pp - WARNING: unquoted file mode on line 28
The command "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'" exited with 1.
~~~

**Comment by bmjen** [comment]
@mnothic Have you had a chance to address the issues on this PR?

**Comment by nibalizer** [comment]
I'm ok with the code/feature but need the cleanups asked for.

**Pull request closed without merging**
