### PR TITLE
Make LDAP section more configurable

### PR DESCRIPTION
**Pull request by voroniys**
Add a possibility for more flexible configuration of LDAP auth

### CODE REVIEW

**Comment by igalic** [comment]
sounds and looks reasonable, but i'd [squash](http://www.git-scm.com/book/en/Git-Tools-Rewriting-History#Squashing-Commits) those three commits down to one.
***
next time you might wanna look into the [github flow](https://guides.github.com/introduction/flow/index.html) workflow, which should make all of this much easier.

**Comment by voroniys** [comment]
unfortunately I don't have direct access to github.com, so I was obliged
to do the changes via editor in github web interface, therefore one commit
per file.

I can redo all this when I'll be @home and don't have network
restrictions, if needed, but I believe this is not a big problem to
implement this pull request with 3 commits.

Let me know what you prefer.

Kind regards,
Stanislav Voroniy.

**Comment by nibalizer** [comment]
lgtm

**Comment by voroniys** [comment]
Merged commits into one

**Comment by igalic** [comment]
@voroniys interesting… now you have *5* commits…

**Comment by voroniys** [comment]
On 7-2-2015 12:12, Igor Galić wrote:
>
> @voroniys <https://github.com/voroniys> interesting… now you have /5/ 
> commits…
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/puppetlabs/puppetlabs-rabbitmq/pull/305#issuecomment-73360088>.
>
Yeah, that is how GIT is working :)

**Comment by cmurphy** [comment]
@voroniys 'merge' is slightly different from 'squash', I would glance at the link about squashing that @igalic posted. This pull request should have only one commit.

**Comment by voroniys** [comment]
Have you tryed it yourself, or this is just a theoretical knowledge?

GIT squash works so:
3 transactions are not removed, but made empty
squashing of 3 transaction creates new one.
this way your work copy is out of sync and to push it to server merge 
transaction is created.

In total you have as a result 5 transactions, but only one has a code 
change, the rest is empty transaction hashes

**Comment by cmurphy** [comment]
Merged via #312

**Pull request closed without merging**
