### PR TITLE
Update apt.pp

### PR DESCRIPTION
**Pull request by Yuav**
MODULES-3439 Update apt repo defaults to correspond with manual from: https://www.rabbitmq.com/install-debian.html

### CODE REVIEW

**Comment by manojsamtani** [comment]
I have tried and was able to resolve this by calling rabbitmq class as

class { 'rabbitmq':
        package_gpg_key => 'http://www.rabbitmq.com/rabbitmq-release-signing-key.asc', }

Because rabbitmq class calling repo/apt.pp from init.pp with package_gpg_key variable which is actually pointing to rabbitmq::params::package_key

So, better to call rabbitmq class as given above example with new key URL

**Comment by hauleth** [comment]
Still doesn't work for me.

**Comment by manojsamtani** [comment]
Please update rabbitmq module as well with following key

class rabbitmq::repo::apt(
  $location    = 'http://www.rabbitmq.com/debian/',
  $release     = 'testing',
  $repos       = 'main',
  $include_src = false,
  #$key         = 'F78372A06FF50C80464FC1B4F7B8CEA6056E8E56',
  **$key         = '0A9AF2115F4687BD29803A206B73A36E6026DFCA',**
  $key_source  = 'http://www.rabbitmq.com/rabbitmq-signing-key-public.asc',

**Comment by hauleth** [comment]
@manojsamtani the issue was with stale machine. Fixed now.

**Comment by DanEEStar** [comment]
Please make a new release with this new signing keys!

**Comment by yrobla** [comment]
I'm hitting the same problem with 5.4.0 , a new release with new keys is needed.

**Comment by acbox** [comment]
+1, please make a new release

**Pull request merged**
