### PR TITLE
Added full fingerprint to be compliant with puppetlabs-apt v1.8

### PR DESCRIPTION
**Pull request by mvisonneau**
This avoids warnings

### CODE REVIEW

**Comment by cyberious** [comment]
Can you please squash in one passing commit.

**Comment by cmurphy** [comment]
Can you also bump the minimum apt dependency to 1.8.0 in the metadata.json, as that was then this support was added?

**Comment by mvisonneau** [comment]
There you go !

**Comment by Zlo** [comment]
The long fingerprint should work fine with puppetlabs-apt v1.0, it is just that v1.8 started warning about short fingerprints. The dependency bump is not necessary IMHO.

**Pull request merged**
