### PR TITLE
Fix for fixes for file_limit

### PR DESCRIPTION
**Pull request by aldavud**
The fix was not correct, and was missing test for invalid values.

### CODE REVIEW

**Comment by aldavud** [comment]
Fixing #319. Great community work on helping me improve my patch...

**Comment by jonnytpuppet** [comment]
Hi There

Thanks for your contribution.

It would be appreciated if you could please provide some details on what was wrong with the original implementation, and how your changes have fixed it.

Thanks!

**Comment by aldavud** [comment]
Hi Jonny

The current solution checks if the number passed in is an integer via the stdlib is_integer function. The issue is that is_integer also accepts integers below zero, for example -42, which in turn is not a valid argument for the limits.conf file. You can also compare this with the test I added.

**Comment by bmjen** [comment]
@aldavud Thanks for the contribution and the explanation. This does seem like a nice validation update to have. Can you please rebase?

**Comment by aldavud** [comment]
@bmjen there you go.

**Comment by bmjen** [comment]
Hi @aldavud, your unit tests for `file_limit` are failing now.

**Comment by aldavud** [comment]
Hi @bmjen thanks for the heads up. I did a far too simple rebase and missed that there were now more contexts for other distros.

All is well now :)

**Pull request merged**
