### PR TITLE
rabbitmq signing key has moved

### PR DESCRIPTION
**Pull request by igalic**
(fingerprint is still the same)

### CODE REVIEW

**Comment by EmilienM** [comment]
that's not enough, you'll need to patch manifests/params.pp: and update all unit tests.

**Comment by alexjfisher** [comment]
@igalic Are you sure about the fingerprint?
https://github.com/puppetlabs/puppetlabs-rabbitmq/pull/477 has it updated.

**Comment by bilsch** [comment]
while you are looking at this one, mind looking at my PR - seems I'm also suffering from travis build failures - #474

**Comment by michaelklishin** [comment]
Heads-up, rabbitmq.com apt repo was [re-signed with the new release key](https://groups.google.com/d/msg/rabbitmq-users/BO5cmEsdEhc/Jupz1_Q4AwAJ).

**Pull request closed without merging**
