### PR TITLE
Added ulimit support

### PR DESCRIPTION
**Pull request by deviantony**
Based on #215 with the updated suggestions.

### CODE REVIEW

**Comment by cmurphy** [comment]
Looks like there's a couple of lint errors.

**Comment by deviantony** [comment]
I've fixed the lint errors, sorry for that.

**Comment by igalic** [comment]
@deviantony would you very much mind [squashing](http://www.git-scm.com/book/en/Git-Tools-Rewriting-History#Squashing-Commits) those commits down to one?

**Comment by deviantony** [comment]
@igalic First squash here, was pretty chaotic but seems ok !

**Comment by cmurphy** [comment]
@deviantony thanks!

**Pull request merged**
