### PR TITLE
ability to set management_hostname in rabbitmqadmin.conf

### PR DESCRIPTION
**Pull request by tampakrap**

### CODE REVIEW

**Comment by hunner** [comment]
Could you also provide docs for this? Thanks!

**Comment by bmjen** [comment]
Thanks for the contribution @tamaskozak! In order to default the parameters the way you are doing it. You will have to add the parameter to `manifest/params.pp` with a default.

Also, please add documentation for the new parameter in the README. Thanks!

**Comment by tampakrap** [comment]
sure, improved. Review again please

**Comment by bmjen** [comment]
Thanks @tampakrap !

**Pull request merged**
