### PR TITLE
add --tlsv1.1 flag to curl download of rabbitmqadmin so that the http…

### PR DESCRIPTION
**Pull request by jpackagejasonc**
…s server doesn't reject the request with newer rabbitmq-server

### CODE REVIEW

**Comment by hunner** [comment]
Does the rabbitmq server not auto-negotiate the security protocol? Why this flag specifically? What happens on older versions?

**Comment by bmjen** [comment]
Thanks for the contribution @jpackagejasonc! Are you able to address the questions that @hunner asked?

**Comment by jpackagejasonc** [comment]
I can't reproduce the failure anymore with our current setup so I think this is ok to close without merging. thanks for looking!

**Comment by bmjen** [comment]
Thanks for the update @jpackagejasonc!

**Pull request closed without merging**
