### PR TITLE
fix to allow specifying either key_content or package_gpg_key

### PR DESCRIPTION
**Pull request by nnathan**
The example in the README.md is confusing and doesn't work.

1. There is no way to specify $key_content without the apt_key provider complaining (see [here](https://github.com/puppetlabs/puppetlabs-apt/blob/master/lib/puppet/type/apt_key.rb#L22-L29)).

2. Also when specifying the $packaging_gpg_key and setting to a file, you must explicitly set $key_content to undef, otherwise we get stuck in the same issue (this was originally confusing because the example was wrong).

This patch attempts to avoid any confusion and tries to alert the user if there's an invalid combination which will not work with apt_key.

### CODE REVIEW

**Comment by bmjen** [comment]
Fails lint.

This change also removes any kind of validation for $package_gpg_key for non-Debian operating systems.

**Comment by bmjen** [comment]
@nnathan Can you also please rebase from master to pull in some fixes to CI? Thanks!

**Comment by nnathan** [comment]
I just made the patch to address Debian only since I'm not familiar the behaviour with other OSes.

The functionality for non-Debian OSes should remain unaffected.

**Comment by bmjen** [comment]
@nnathan Can you also squash your two commits?

**Comment by bmjen** [comment]
@nnathan Also, it would have been better to do a rebase instead of a merge of master.

**Comment by jonnytpuppet** [comment]
Hi There

I'm closing this PR due to inactivity as well as the concerns raised by @bmjen 
Please re-submit your PR if you would still like this functionality included with the concern saddressed.

Thanks!

**Pull request closed without merging**
